### ISSUE TITLE
Bundle name fails for lunetics/locale-bundle

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony/flex#160]
When doing `composer req lunetics/locale-bundle` the composer part works fine, but somehow the bundle name generation fails:
```
maximilian@maximilian-ThinkPad-T540p:~/Konferenzen/slides/2017/NeverCodeAlone/nevercodealon-demo-app$ composer req lunetics/locale-bundle
Using version ^2.5 for lunetics/locale-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing symfony/intl (v3.3.9)
    Downloading: 100%         

  - Installing symfony/polyfill-intl-icu (v1.5.0)
    Loading from cache

  - Installing lunetics/locale-bundle (2.5.3)
    Loading from cache

symfony/intl suggests installing ext-intl (to use the component with locales other than "en")
symfony/polyfill-intl-icu suggests installing ext-intl (For best performance)
lunetics/locale-bundle suggests installing ext-intl (Needed for displaying the country name in the locale language)
Writing lock file
Generating autoload files
Symfony operations: 1 recipe
  - Configuring lunetics/locale-bundle (2.5.3): From auto-generated recipe
Executing script make cache-warmup [KO]
 [KO]
Script make cache-warmup returned with error code 2
!!  PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "LocaleBundle" from namespace "Lunetics\LocaleBundle".
!!  Did you forget a "use" statement for "Symfony\Component\Intl\ResourceBundle\LocaleBundle"? in /home/maximilian/Konferenzen/slides/2017/NeverCodeAlone/nevercodealon-demo-app/src/Kernel.php:32
!!  Stack trace:
!!  #0 /home/maximilian/Konferenzen/slides/2017/NeverCodeAlone/nevercodealon-demo-app/vendor/symfony/http-kernel/Kernel.php(450): App\Kernel->registerBundles()
!!  #1 /home/maximilian/Konferenzen/slides/2017/NeverCodeAlone/nevercodealon-demo-app/vendor/symfony/http-kernel/Kernel.php(116): Symfony\Component\HttpKernel\Kernel->initializeBundles()
!!  #2 /home/maximilian/Konferenzen/slides/2017/NeverCodeAlone/nevercodealon-demo-app/vendor/symfony/framework-bundle/Console/Application.php(69): Symfony\Component\HttpKernel\Kernel->boot()
!!  #3 /home/maximilian/Konferenzen/slides/2017/NeverCodeAlone/nevercodealon-demo-app/vendor/symfony/console/Application.php(125): Symfony\Bundle\Framew in /home/maximilian/Konferenzen/slides/2017/NeverCodeAlone/nevercodealon-demo-app/src/Kernel.php on line 32
!!  
!!  Makefile:15: recipe for target 'cache-clear' failed
!!  
!!  make: *** [cache-clear] Error 255
!!  
!!  

Installation failed, reverting ./composer.json to its original content.
```
when i look into the `bundles.php` i see:

```
    'Lunetics\LocaleBundle\LocaleBundle' => ['all' => true],
    'Lunetics\LocaleBundle\LuneticsLocaleBundle' => ['all' => true],
```

which seems to be a kind of a duplication

**Comment by ElectricMaxxx** [comment]
Same happens for `jms/serializer-bundle`.

**Comment by stof** [comment]
Well, this is because it uses an autogenerated recipe, and it configured the wrong class there.
However, it is weird that it registers the class if it does not exist. It should register none if it fails to find them.

**Comment by teohhanhui** [comment]
Same problem for [intaro/custom-index-bundle](https://github.com/intaro/custom-index-bundle)

In `config/bundles.php`:

```php
<?php

return [
    ...
    'Intaro\CustomIndexBundle\CustomIndexBundle' => ['all' => true],
    'Intaro\CustomIndexBundle\IntaroCustomIndexBundle' => ['all' => true],
    ...
];
```

Related to #108 and #135

**Comment by ElectricMaxxx** [comment]
I think those things can be tested on PR. Simply create a skeleton, cd, require with ENV configurarion to the PR. Mostly there is an Error on cache-warmup and the composer.json was not changed.

**Comment by ElectricMaxxx** [comment]
I mean tested by the contributor or on CI.
