### ISSUE TITLE
Exception during package removal

### ISSUE THREAD

**Issue by aik099** [symfony/flex#171]
I've installed `sensio/generator-bundle` package with `composer require sensio/generator-bundle` without issues. However, when I tried to remove it using `composer remove sensio/generator-bundle` command I've got this error:

```
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "SensioGeneratorBundle" from namespace "Sensio\Bundle\GeneratorBundle".
```

Complete output:
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 0 updates, 1 removal
  - Removing sensio/generator-bundle (v3.1.6)
Writing lock file
Generating autoload files
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "SensioGeneratorBundle" from namespace "Sensio\Bundle\GeneratorBundle".
Did you forget a "use" statement for another namespace? in .../app/AppKernel.php:28
Stack trace:
#0 .../vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(450): AppKernel->registerBundles()
#1 .../vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(116): Symfony\Component\HttpKernel\Kernel->initializeBundles()
#2 .../vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(69): Symfony\Component\HttpKernel\Kernel->boot()
#3 .../vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(125): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Sy in .../app/AppKernel.php on line 28

Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "SensioGeneratorBundle" from namespace "Sensio\Bundle\GeneratorBundle".
Did you forget a "use" statement for another namespace? in .../app/AppKernel.php on line 28

Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "SensioGeneratorBundle" from namespace "Sensio\Bundle\GeneratorBundle".
Did you forget a "use" statement for another namespace? in .../app/AppKernel.php on line 28

Call Stack:
    0.0312    2002112   1. Symfony\Component\Debug\ErrorHandler->handleException(class Symfony\Component\Debug\Exception\ClassNotFoundException, ???) .../vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php:0


Variables in local scope (#1):
  $e = class Symfony\Component\Debug\Exception\ClassNotFoundException { protected $message = 'Attempted to load class "SensioGeneratorBundle" from namespace "Sensio\\Bundle\\GeneratorBundle".\nDid you forget a "use" statement for another namespace?'; private ${Exception}:string = ''; protected $code = 0; protected $file = '.../app/AppKernel.php'; protected $line = 28; private ${Exception}:trace = array (0 => array (...), 1 => array (...), 2 => array (...), 3 => array (...), 4 => array (...)); private ${Exception}:previous = NULL; protected $severity = 1 }
  $error = array ('type' => 1, 'message' => 'Class \'Sensio\\Bundle\\GeneratorBundle\\SensioGeneratorBundle\' not found', 'file' => '.../app/AppKernel.php', 'line' => 28)
  $exception = class Symfony\Component\Debug\Exception\ClassNotFoundException { protected $message = 'Attempted to load class "SensioGeneratorBundle" from namespace "Sensio\\Bundle\\GeneratorBundle".\nDid you forget a "use" statement for another namespace?'; private ${Exception}:string = ''; protected $code = 0; protected $file = '.../app/AppKernel.php'; protected $line = 28; private ${Exception}:trace = array (0 => array (...), 1 => array (...), 2 => array (...), 3 => array (...), 4 => array (...)); private ${Exception}:previous = NULL; protected $severity = 1 }
  $handler = class Symfony\Component\Debug\FatalErrorHandler\ClassNotFoundFatalErrorHandler {  }
  $handlerException = *uninitialized*
  $message = 'Class \'Sensio\\Bundle\\GeneratorBundle\\SensioGeneratorBundle\' not found'
  $type = 1
```

**Comment by aik099** [comment]
Ups, my bad. I was executing `composer remove ...` command in regular Symfony 3.3 project (not built by Symfony Flex) and haven't removed bundle registration.

All works fine for that package in Symfony Flex built project.
