### ISSUE TITLE
'composer require' broken with Flex 1.0.52

### ISSUE THREAD

**Issue by cjunge-work** [symfony/flex#252]
Typing `composer require` with Flex 1.0.52 is broken.
```
$ composer require
PHP Fatal error:  Uncaught TypeError: Return value of Symfony\Flex\Unpack\Operation::getPackages() must be of the type array, null returned in /home/cameron/Development/sf4-cli/vendor/symfony/flex/src/Unpack/Operation.php:37
Stack trace:
#0 /home/cameron/Development/sf4-cli/vendor/symfony/flex/src/Unpacker.php(38): Symfony\Flex\Unpack\Operation->getPackages()
#1 /home/cameron/Development/sf4-cli/vendor/symfony/flex/src/Command/RequireCommand.php(51): Symfony\Flex\Unpacker->unpack(Object(Symfony\Flex\Unpack\Operation))
#2 phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php(266): Symfony\Flex\Command\RequireCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(861): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 phar:///usr/local/bin/composer/vendor/symfony/c in /home/cameron/Development/sf4-cli/vendor/symfony/flex/src/Unpack/Operation.php on line 37
```
Tested this with the `symfony/skeleton` demo app.

The expected behaviour is for Composer to ask for a package to search for.

**Comment by sstok** [comment]
Confirmed. it's broken.
