### ISSUE TITLE
Class 'Symfony\Flex\PluginEvents' not found

### ISSUE THREAD

**Issue by garak** [symfony/flex#263]
Just upgraded a project of mine from flex v1.0.42 to v1.0.55, I'm getting this error:
>Fatal error: Uncaught Error: Class 'Symfony\Flex\PluginEvents' not found in /user/myproject/vendor/symfony/flex/src/Flex.php:439

Full output:
```
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 128 installs, 0 updates, 0 removals
  - Installing symfony/flex (v1.0.55): Loading from cache

Fatal error: Uncaught Error: Class 'Symfony\Flex\PluginEvents' not found in /user/myproject/vendor/symfony/flex/src/Flex.php:439
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(378): Symfony\Flex\Flex::getSubscribedEvents()
#1 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(239): Composer\EventDispatcher\EventDispatcher->addSubscriber(Object(Symfony\Flex\Flex))
#2 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(205): Composer\Plugin\PluginManager->addPlugin(Object(Symfony\Flex\Flex))
#3 phar:///usr/local/bin/composer/src/Composer/Installer/PluginInstaller.php(63): Composer\Plugin\PluginManager->registerPackage(Object(Composer\Package\CompletePackage), true)
#4 phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php(173): Composer\Installer\PluginInstaller->install(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\Package\CompletePackage))
#5 phar:///usr/local/bin/composer/src/Composer/ in /user/myproject/vendor/symfony/flex/src/Flex.php on line 439

```

**Comment by nicolas-grekas** [comment]
fixed by #264 and released, thanks
