### ISSUE TITLE
Error while installing symfony/flex

### ISSUE THREAD

**Issue by marcw** [symfony/flex#348]
I just bumped into this issue while trying to install flex. 

```
~/work/websites/www.audiencehero.localhost (master↑⚡) composer update --no-scripts --prefer-stable                                                                                                                                                         !11405
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 18 updates, 0 removals
  - Installing symfony/flex (v1.0.78): Loading from cache
PHP Fatal error:  Uncaught Error: Cannot use object of type Composer\Repository\VcsRepository as array in /Users/marc/work/websites/www.audiencehero.localhost/vendor/symfony/flex/src/Flex.php:635
Stack trace:
#0 /Users/marc/work/websites/www.audiencehero.localhost/vendor/symfony/flex/src/Flex.php(180): Symfony\Flex\Flex->populateRepoCacheDir()
#1 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(236): Symfony\Flex\Flex->activate(Object(Composer\Composer), Object(Composer\IO\ConsoleIO))
#2 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(205): Composer\Plugin\PluginManager->addPlugin(Object(Symfony\Flex\Flex))
#3 phar:///usr/local/bin/composer/src/Composer/Installer/PluginInstaller.php(63): Composer\Plugin\PluginManager->registerPackage(Object(Composer\Package\CompletePackage), true)
#4 phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php(173): Composer\Installer\PluginInstaller->install(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\Pac in /Users/marc/work/websites/www.audiencehero.localhost/vendor/symfony/flex/src/Flex.php on line 635

Fatal error: Uncaught Error: Cannot use object of type Composer\Repository\VcsRepository as array in /Users/marc/work/websites/www.audiencehero.localhost/vendor/symfony/flex/src/Flex.php:635
Stack trace:
#0 /Users/marc/work/websites/www.audiencehero.localhost/vendor/symfony/flex/src/Flex.php(180): Symfony\Flex\Flex->populateRepoCacheDir()
#1 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(236): Symfony\Flex\Flex->activate(Object(Composer\Composer), Object(Composer\IO\ConsoleIO))
#2 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(205): Composer\Plugin\PluginManager->addPlugin(Object(Symfony\Flex\Flex))
#3 phar:///usr/local/bin/composer/src/Composer/Installer/PluginInstaller.php(63): Composer\Plugin\PluginManager->registerPackage(Object(Composer\Package\CompletePackage), true)
#4 phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php(173): Composer\Installer\PluginInstaller->install(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\Pac in /Users/marc/work/websites/www.audiencehero.localhost/vendor/symfony/flex/src/Flex.php on line 63
```

**Comment by CagatayUlubay** [comment]
Just wanted to create a fresh new project and also got an install error:

$ composer create-project symfony/website-skeleton xxx
Installing symfony/website-skeleton (v4.0.5)
  - Installing symfony/website-skeleton (v4.0.5): Downloading (100%)
Created project in xxx
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 90 installs, 0 updates, 0 removals
  - Installing ocramius/package-versions (1.3.0): Loading from cache
  - Installing symfony/flex (v1.0.78): Downloading (100%)
PHP Fatal error:  Cannot declare class Symfony\Flex\Command\RemoveCommand, because the name is already in use in C:\htdocs\xxx\vendor\symfony\flex\src\Command\RemoveCommand.php on line 36

Fatal error: Cannot declare class Symfony\Flex\Command\RemoveCommand, because the name is already in use in C:\htdocs\xxx\vendor\symfony\flex\src\Command\RemoveCommand.php on line 36

**Comment by fabpot** [comment]
Usually, that happens when you try to create a project within another one.

**Comment by marcw** [comment]
It was a conflict with wikimedia/composer-merge-plugin. I had to remove the composer-merge-plugin specific section of the composer.json file, and then install flex.

**Comment by vodoanthanh093** [comment]
If you use window, you should start wampserver before.
