### ISSUE TITLE
Namespace fail

### ISSUE THREAD

**Issue by GuigZ-** [symfony/flex#372]
Hey,

After a conversation with @dunglas, i open this issue.

This case is strange, if i use namespace should be not loaded with composer i have one error.
I share a repo to try this : https://github.com/GuigZ-/symfony-flex-fail-namespace

My error is : 

```APP_ENV=dev bin/console --env=dev                                                                                                                                                           [±master ●]
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "FidryAliceDataFixturesBundle" from namespace "Fidry\AliceDataFixtures\Bridge\Symfony".
Did you forget a "use" statement for another namespace? in /Users/guigz/Workspace/tmp/src/Kernel.php:33
Stack trace:
#0 /Users/guigz/Workspace/tmp/vendor/symfony/http-kernel/Kernel.php(403): App\Kernel->registerBundles()
#1 /Users/guigz/Workspace/tmp/vendor/symfony/http-kernel/Kernel.php(122): Symfony\Component\HttpKernel\Kernel->initializeBundles()
#2 /Users/guigz/Workspace/tmp/vendor/symfony/framework-bundle/Console/Application.php(64): Symfony\Component\HttpKernel\Kernel->boot()
#3 /Users/guigz/Workspace/tmp/vendor/symfony/console/Application.php(143): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /Users/guigz/Workspace/tmp/bin/console(39): Symfony\Component\Console\Application->run(Object(Symfony\Component\Con in /Users/guigz/Workspace/tmp/src/Kernel.php on line 33

Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "FidryAliceDataFixturesBundle" from namespace "Fidry\AliceDataFixtures\Bridge\Symfony".
Did you forget a "use" statement for another namespace? in /Users/guigz/Workspace/tmp/src/Kernel.php on line 33

Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "FidryAliceDataFixturesBundle" from namespace "Fidry\AliceDataFixtures\Bridge\Symfony".
Did you forget a "use" statement for another namespace? in /Users/guigz/Workspace/tmp/src/Kernel.php on line 33

Call Stack:
    0.0257    1911144   1. Symfony\Component\Debug\ErrorHandler->handleException() /Users/guigz/Workspace/tmp/vendor/symfony/debug/ErrorHandler.php:0

```

**Comment by stof** [comment]
Well, your `config/bundles.php` contains `Fidry\AliceDataFixtures\Bridge\Symfony\FidryAliceDataFixturesBundle`, while the composer.json does not require Alice at all. You should check where this comes from (I cannot do it for you, as your reproducing repo has a single commit with the final state and I don't know which commands you ran to build it)

**Comment by GuigZ-** [comment]
I just install vendor with : `composer install --no-dev --no-scripts` because i don't use dev-vendor on my prod.

**Comment by weaverryan** [comment]
I think Stof is saying that the composer.json file of the linked repo doesn’t contain this bundle at all - in require or require dev. Maybe you forgot to add it in the test repo?

**Comment by GuigZ-** [comment]
Oh sorry,

i push with the new composer.json.

**Comment by GuigZ-** [comment]
Up ? :(

**Comment by xabbuh** [comment]
How did you execute `bin/console`? Is it run in the `dev` environment while dev dependencies are not installed?

**Comment by stof** [comment]
@GuigZ- what is the command you are running when getting this fatal error ?

**Comment by GuigZ-** [comment]
`APP_ENV=dev bin/console cache:clear` for example

**Comment by xabbuh** [comment]
If you did not install the dev dependencies, you shouldn't run the application in the `dev` environment. Use the `prod` environment now:

```
APP_ENV=prod bin/console cache:clear
```

**Comment by GuigZ-** [comment]
The problème is not here... the problem that php should not resolve my namepsace in bundles.php if the vendor is not installed.

I just set this process to throw this error :)

**Comment by GuigZ-** [comment]
Sorry i close this issue, because, the bug is my brain >< sorry.
