### ISSUE TITLE
Flex breaks composer update

### ISSUE THREAD

**Issue by derrabus** [symfony/flex#571]
I currently cannot update any of my Flex-based projects. Even bootstrapping new projects is broken:

```
$ symfony new test-project
* Creating a new Symfony project with Composer
  (running /usr/local/bin/composer create-project symfony/skeleton test-project)

Installing symfony/skeleton (v4.3.99)
  - Installing symfony/skeleton (v4.3.99): Loading from cache
Created project in test-project
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing symfony/flex (v1.4.8): Loading from cache
Symfony operations: 1 recipe (5afac8bbf75e39a95916954b0212edf1)
  - Configuring symfony/flex (>=1.0): From github.com/symfony/recipes:master
Loading composer repositories with package information
Updating dependencies (including require-dev)
PHP Fatal error:  Uncaught Error: Call to a member function getVersions() on null in /Volumes/Projects/Misc/test-project/vendor/symfony/flex/src/Cache.php:118
Stack trace:
#0 /Volumes/Projects/Misc/test-project/vendor/symfony/flex/src/Cache.php(58): Symfony\Flex\Cache->getVersions()
#1 /Volumes/Projects/Misc/test-project/vendor/symfony/flex/src/TruncatedComposerRepository.php(41): Symfony\Flex\Cache->removeLegacyTags(Array)
#2 phar:///usr/local/Cellar/composer/1.9.1/bin/composer/src/Composer/Repository/ComposerRepository.php(358): Symfony\Flex\TruncatedComposerRepository->fetchFile('http://repo.pac...', 'provider-symfon...', '658e184eec78ca5...', false)
#3 /Volumes/Projects/Misc/test-project/vendor/symfony/flex/src/Flex.php(538): Composer\Repository\ComposerRepository->whatProvides(Object(Composer\DependencyResolver\Pool), 'symfony/framewo...', false)
#4 phar:///usr/local/Cellar/composer/1.9.1/bin/composer/src/Composer/DependencyResolver/Pool.php(204): class@anonymous->whatProvides(Object(Composer\DependencyResolver\Pool), 'sy in /Volumes/Projects/Misc/test-project/vendor/symfony/flex/src/Cache.php on line 118

Fatal error: Uncaught Error: Call to a member function getVersions() on null in /Volumes/Projects/Misc/test-project/vendor/symfony/flex/src/Cache.php:118
Stack trace:
#0 /Volumes/Projects/Misc/test-project/vendor/symfony/flex/src/Cache.php(58): Symfony\Flex\Cache->getVersions()
#1 /Volumes/Projects/Misc/test-project/vendor/symfony/flex/src/TruncatedComposerRepository.php(41): Symfony\Flex\Cache->removeLegacyTags(Array)
#2 phar:///usr/local/Cellar/composer/1.9.1/bin/composer/src/Composer/Repository/ComposerRepository.php(358): Symfony\Flex\TruncatedComposerRepository->fetchFile('http://repo.pac...', 'provider-symfon...', '658e184eec78ca5...', false)
#3 /Volumes/Projects/Misc/test-project/vendor/symfony/flex/src/Flex.php(538): Composer\Repository\ComposerRepository->whatProvides(Object(Composer\DependencyResolver\Pool), 'symfony/framewo...', false)
#4 phar:///usr/local/Cellar/composer/1.9.1/bin/composer/src/Composer/DependencyResolver/Pool.php(204): class@anonymous->whatProvides(Object(Composer\DependencyResolver\Pool), 'sy in /Volumes/Projects/Misc/test-project/vendor/symfony/flex/src/Cache.php on line 118

  unable to run /usr/local/bin/composer create-project symfony/skeleton test-project : exit status 255
```

The cause of this seems to be that https://flex.symfony.com/versions.json is currently sending empty version numbers.

<img width="388" alt="Bildschirmfoto 2019-11-17 um 20 04 45" src="https://user-images.githubusercontent.com/1506493/69012405-a870a680-0975-11ea-983a-3c7e2ae7ac35.png">

**Comment by aurimasniekis** [comment]
It brakes everything can do nothing related to compsoer

**Comment by aurimasniekis** [comment]
Quick fix for everybody who is effected to fix install:

In file: `vendor/symfony/flex/src/Cache.php:124`

![image](https://user-images.githubusercontent.com/15481/69012595-6fcdce80-096f-11ea-9163-1a21adfb5556.png)

**Comment by Taluu** [comment]
Would be better imo to do a `continue;` instead.

**Comment by jacquelotjeff** [comment]
It works well with "continue;" instruction.

```php
if ($v === '') { continue; }
```

**Comment by fogs** [comment]
I am having the exact same issue - only documented it here: https://github.com/symfony/website-skeleton/issues/244

**Comment by belendel** [comment]
Same issue

**Comment by fabpot** [comment]
Fixed now.

**Comment by derrabus** [comment]
That was fast! Thanks a lot.
