### ISSUE TITLE
symfony/flex throwing error after fresh symfony install

### ISSUE THREAD

**Issue by naroga** [symfony/flex#689]
> PHP 7.3.23-1+ubuntu20.04.1+deb.sury.org+1 (cli) (built: Oct  6 2020 11:36:44) ( NTS )
> Copyright (c) 1997-2018 The PHP Group
> Zend Engine v3.3.23, Copyright (c) 1998-2018 Zend Technologies
>     with Zend OPcache v7.3.23-1+ubuntu20.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

Error: PHP Fatal error:  Uncaught Error: Call to a member function getPrettyString() on string in /<basePath>/vendor/symfony/flex/src/Unpacker.php:153

Stacktrace:

```
PHP Fatal error:  Uncaught Error: Call to a member function getPrettyString() on string in <basePath>/vendor/symfony/flex/src/Unpacker.php:153
Stack trace:
#0 <basePath>/vendor/symfony/flex/src/Command/UnpackCommand.php(79): Symfony\Flex\Unpacker->unpack(Object(Symfony\Flex\Unpack\Operation))
#1 <basePath>/vendor/symfony/flex/src/Command/RequireCommand.php(63): Symfony\Flex\Command\UnpackCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\O
utput\ConsoleOutput))
#2 phar:///mnt/c/composer/composer.phar/vendor/symfony/console/Command/Command.php(245): Symfony\Flex\Command\RequireCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\Console
Output))
#3 phar:///mnt/c/composer/composer.phar/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Obje in /home/naroga/Projects/crawly/madeiramadeira/vendor/symfony/flex/src/Unpacker.php on line 153

Fatal error: Uncaught Error: Call to a member function getPrettyString() on string in <basePath>/vendor/symfony/flex/src/Unpacker.php:153
Stack trace:
#0 <basePath>/vendor/symfony/flex/src/Command/UnpackCommand.php(79): Symfony\Flex\Unpacker->unpack(Object(Symfony\Flex\Unpack\Operation))
#1 <basePath>/vendor/symfony/flex/src/Command/RequireCommand.php(63): Symfony\Flex\Command\UnpackCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\O
utput\ConsoleOutput))
#2 phar:///mnt/c/composer/composer.phar/vendor/symfony/console/Command/Command.php(245): Symfony\Flex\Command\RequireCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\Console
Output))
#3 phar:///mnt/c/composer/composer.phar/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Obje in /home/naroga/Projects/crawly/madeiramadeira/vendor/symfony/flex/src/Unpacker.php on line 153
```

To reproduce:

- `symfony new <project name> && cd <project name> && composer req orm`

Symfony CLI version: Symfony CLI version v4.19.0 (c) 2017-2020 Symfony SAS

**Comment by nicolas-grekas** [comment]
Please upgrade, that should be fixed already.

**Comment by nicolas-grekas** [comment]
FYI I just tried `symfony new toto && cd toto && composer req orm` with composer 1 & 2, it works now.

**Comment by naroga** [comment]
I must've had something cached on my composer local directory. I just cleared the composer cache, ran a composer update and the error went away. Thanks.
