### ISSUE TITLE
.env file is missing after creating project

### ISSUE THREAD

**Issue by torbenbr** [symfony/flex#719]
```bash
$ composer create-project symfony/skeleton playground
Creating a "symfony/skeleton" project at "./playground"
Installing symfony/skeleton (v5.1.99)
  - Installing symfony/skeleton (v5.1.99): Extracting archive
Created project in /Users/torbenbruemmer/Workspace/playground
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking symfony/flex (v1.10.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing symfony/flex (v1.10.0): Extracting archive
Failed to download recipe: Resolving timed out after 10008 milliseconds

Run composer recipes at any time to see the status of your Symfony recipes.

Loading composer repositories with package information
Resolving timed out after 10003 milliseconds
https://flex.symfony.com/versions.json could not be fully loaded, package information was loaded from the local cache and may be out of date
Restricting packages listed in "symfony/symfony" to "5.1.*"
Updating dependencies
Lock file operations: 31 installs, 0 updates, 0 removals
  - Locking psr/cache (1.0.1)
  - Locking psr/container (1.0.0)
  - Locking psr/event-dispatcher (1.0.0)
  - Locking psr/log (1.1.3)
  - Locking symfony/cache (v5.1.8)
  - Locking symfony/cache-contracts (v2.2.0)
  - Locking symfony/config (v5.1.8)
  - Locking symfony/console (v5.1.8)
  - Locking symfony/dependency-injection (v5.1.8)
  - Locking symfony/deprecation-contracts (v2.2.0)
  - Locking symfony/dotenv (v5.1.8)
  - Locking symfony/error-handler (v5.1.8)
  - Locking symfony/event-dispatcher (v5.1.8)
  - Locking symfony/event-dispatcher-contracts (v2.2.0)
  - Locking symfony/filesystem (v5.1.8)
  - Locking symfony/finder (v5.1.8)
  - Locking symfony/framework-bundle (v5.1.8)
  - Locking symfony/http-client-contracts (v2.3.1)
  - Locking symfony/http-foundation (v5.1.8)
  - Locking symfony/http-kernel (v5.1.8)
  - Locking symfony/polyfill-intl-grapheme (v1.20.0)
  - Locking symfony/polyfill-intl-normalizer (v1.20.0)
  - Locking symfony/polyfill-mbstring (v1.20.0)
  - Locking symfony/polyfill-php73 (v1.20.0)
  - Locking symfony/polyfill-php80 (v1.20.0)
  - Locking symfony/routing (v5.1.8)
  - Locking symfony/service-contracts (v2.2.0)
  - Locking symfony/string (v5.1.8)
  - Locking symfony/var-dumper (v5.1.8)
  - Locking symfony/var-exporter (v5.1.8)
  - Locking symfony/yaml (v5.1.8)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 31 installs, 0 updates, 0 removals
  - Installing psr/cache (1.0.1): Extracting archive
  - Installing symfony/cache-contracts (v2.2.0): Extracting archive
  - Installing symfony/polyfill-php80 (v1.20.0): Extracting archive
  - Installing symfony/polyfill-mbstring (v1.20.0): Extracting archive
  - Installing symfony/polyfill-intl-normalizer (v1.20.0): Extracting archive
  - Installing symfony/polyfill-intl-grapheme (v1.20.0): Extracting archive
  - Installing symfony/string (v5.1.8): Extracting archive
  - Installing psr/container (1.0.0): Extracting archive
  - Installing symfony/service-contracts (v2.2.0): Extracting archive
  - Installing symfony/polyfill-php73 (v1.20.0): Extracting archive
  - Installing symfony/console (v5.1.8): Extracting archive
  - Installing symfony/deprecation-contracts (v2.2.0): Extracting archive
  - Installing symfony/dotenv (v5.1.8): Extracting archive
  - Installing psr/event-dispatcher (1.0.0): Extracting archive
  - Installing symfony/event-dispatcher-contracts (v2.2.0): Extracting archive
  - Installing symfony/routing (v5.1.8): Extracting archive
  - Installing symfony/http-foundation (v5.1.8): Extracting archive
  - Installing symfony/http-client-contracts (v2.3.1): Extracting archive
  - Installing symfony/event-dispatcher (v5.1.8): Extracting archive
  - Installing symfony/var-dumper (v5.1.8): Extracting archive
  - Installing psr/log (1.1.3): Extracting archive
  - Installing symfony/error-handler (v5.1.8): Extracting archive
  - Installing symfony/http-kernel (v5.1.8): Extracting archive
  - Installing symfony/finder (v5.1.8): Extracting archive
  - Installing symfony/filesystem (v5.1.8): Extracting archive
  - Installing symfony/dependency-injection (v5.1.8): Extracting archive
  - Installing symfony/config (v5.1.8): Extracting archive
  - Installing symfony/var-exporter (v5.1.8): Extracting archive
  - Installing symfony/cache (v5.1.8): Extracting archive
  - Installing symfony/framework-bundle (v5.1.8): Extracting archive
  - Installing symfony/yaml (v5.1.8): Extracting archive
Generating optimized autoload files
28 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

Symfony operations: 3 recipes (9889c421e07f5b22b7ba13f0c66c3830)
  - Configuring symfony/framework-bundle (>=5.1): From github.com/symfony/recipes:master
  - Configuring symfony/console (>=5.1): From github.com/symfony/recipes:master
  - Configuring symfony/routing (>=5.1): From github.com/symfony/recipes:master
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  PHP Fatal error:  Uncaught Symfony\Component\Dotenv\Exception\PathException: Unable to read the "/Users/torbenbr/Workspace/playground/.env" environment file. in /Users/torbenbr/Workspace/playground/vendor/symfony/dotenv/Dotenv.php:565
!!  Stack trace:
!!  #0 /Users/torbenbruemmer/Workspace/playground/vendor/symfony/dotenv/Dotenv.php(92): Symfony\Component\Dotenv\Dotenv->doLoad(false, Array)
!!  #1 /Users/torbenbruemmer/Workspace/playground/vendor/symfony/dotenv/Dotenv.php(114): Symfony\Component\Dotenv\Dotenv->load('/Users/torbenbr...')
!!  #2 /Users/torbenbruemmer/Workspace/playground/vendor/symfony/dotenv/Dotenv.php(157): Symfony\Component\Dotenv\Dotenv->loadEnv('/Users/torbenbr...', 'APP_ENV', 'dev', Array)
!!  #3 /Users/torbenbruemmer/Workspace/playground/bin/console(31): Symfony\Component\Dotenv\Dotenv->bootEnv('/Users/torbenbr...')
!!  #4 {main}
!!    thrown in /Users/torbenbruemmer/Workspace/playground/vendor/symfony/dotenv/Dotenv.php on line 565
!!  
!!  Fatal error: Uncaught Symfony\Component\Dotenv\Exception\PathException: Unable to read the "/Users/torbenbruemmer/Workspace/playground/.env" environment file. in /Users/torbenbruemmer/Workspace/playground/vendor/symfony/dotenv/Dotenv.php on line 565
!!  
!!  Symfony\Component\Dotenv\Exception\PathException: Unable to read the "/Users/torbenbruemmer/Workspace/playground/.env" environment file. in /Users/torbenbruemmer/Workspace/playground/vendor/symfony/dotenv/Dotenv.php on line 565
!!  
!!  Call Stack:
!!      0.0013     406136   1. {main}() /Users/torbenbruemmer/Workspace/playground/bin/console:0
!!      0.0081    1387472   2. Symfony\Component\Dotenv\Dotenv->bootEnv() /Users/torbenbruemmer/Workspace/playground/bin/console:31
!!      0.0081    1387568   3. Symfony\Component\Dotenv\Dotenv->loadEnv() /Users/torbenbruemmer/Workspace/playground/vendor/symfony/dotenv/Dotenv.php:157
!!      0.0081    1387648   4. Symfony\Component\Dotenv\Dotenv->load() /Users/torbenbruemmer/Workspace/playground/vendor/symfony/dotenv/Dotenv.php:114
!!      0.0081    1388024   5. Symfony\Component\Dotenv\Dotenv->doLoad() /Users/torbenbruemmer/Workspace/playground/vendor/symfony/dotenv/Dotenv.php:92
!!  
!!  
Script @auto-scripts was called via post-update-cmd
```

```bash
$ composer show symfony/flex                                                                                                                                                                                               127 
name     : symfony/flex
descrip. : Composer plugin for Symfony
keywords : 
versions : * v1.10.0
type     : composer-plugin
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
homepage : 
source   : [git] https://github.com/symfony/flex.git e38520236bdc911c2f219634b485bc328746e980
dist     : [zip] https://api.github.com/repos/symfony/flex/zipball/e38520236bdc911c2f219634b485bc328746e980 e38520236bdc911c2f219634b485bc328746e980
path     : /Users/torbenbruemmer/Workspace/playground/vendor/symfony/flex
names    : symfony/flex

support
issues : https://github.com/symfony/flex/issues
source : https://github.com/symfony/flex/tree/v1.10.0

autoload
psr-4
Symfony\Flex\ => src

requires
composer-plugin-api ^1.0|^2.0
php >=7.1

requires (dev)
composer/composer ^1.0.2|^2.0
symfony/dotenv ^4.4|^5.0
symfony/phpunit-bridge ^4.4|^5.0
symfony/process ^3.4|^4.4|^5.0
```

```bash
$  composer --version
Composer version 2.0.7 2020-11-13 17:31:06
```

```bash
$  php -v
PHP 7.4.12 (cli) (built: Oct 29 2020 18:37:21) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Xdebug v2.9.8, Copyright (c) 2002-2020, by Derick Rethans
    with Zend OPcache v7.4.12, Copyright (c), by Zend Technologi
```

**Comment by torbenbr** [comment]
"Fix": https://github.com/composer/composer/issues/9376#issuecomment-719457949
