### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined method Composer\DependencyResolver\Request::getFixedOrLockedPackages()

### ISSUE THREAD

**Issue by bendavies** [symfony/flex#752]
Hi,

Getting this error under the following circumstances: 

```bash
➜  scotam composer --version
Composer version 2.0.12 2021-04-01 10:14:59
➜  scotam symfony version
Symfony CLI version v4.23.4 (2021-04-05T14:17:04+0000 - stable)
```
```bash
➜  symfony new symfony-5.2 --full
* Creating a new Symfony project with Composer
(running /usr/local/bin/composer2 create-project symfony/website-skeleton /Code/foo  --no-interaction)

Creating a "symfony/website-skeleton" project at "./symfony-5.2"
Installing symfony/website-skeleton (v5.2.99)
- Installing symfony/website-skeleton (v5.2.99): Extracting archive
Created project in /Code/foo
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
- Locking symfony/flex (v1.12.2)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
- Installing symfony/flex (v1.12.2): Extracting archive

Symfony operations: 1 recipe (857c08dbc0d576eb977c0c092e632c8e)
- Configuring symfony/flex (>=1.0): From github.com/symfony/recipes:master
Loading composer repositories with package information
Updating dependencies
PHP Fatal error:  Uncaught Error: Call to undefined method Composer\DependencyResolver\Request::getFixedOrLockedPackages() in /Code/foo/vendor/symfony/flex/src/Flex.php:885
Stack trace:
#0 [internal function]: Symfony\Flex\Flex->truncatePackages(Object(Composer\Plugin\PrePoolCreateEvent))
#1 phar:///usr/local/bin/composer2/src/Composer/EventDispatcher/EventDispatcher.php(170): call_user_func(Array, Object(Composer\Plugin\PrePoolCreateEvent))
#2 phar:///usr/local/bin/composer2/src/Composer/EventDispatcher/EventDispatcher.php(91): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Plugin\PrePoolCreateEvent))
#3 phar:///usr/local/bin/composer2/src/Composer/DependencyResolver/PoolBuilder.php(236): Composer\EventDispatcher\EventDispatcher->dispatch('pre-pool-create', Object(Composer\Plugin\PrePoolCreateEvent))
#4 phar:///usr/local/bin/composer2/src/Composer/Repository/RepositorySet.php(233): Composer\DependencyResolver\PoolBuilder->buildPool(Array, Object(Composer\DependencyResolver\Reques in /Code/foo/vendor/symfony/flex/src/Flex.php on line 885

Fatal error: Uncaught Error: Call to undefined method Composer\DependencyResolver\Request::getFixedOrLockedPackages() in /Code/foo/vendor/symfony/flex/src/Flex.php:885
Stack trace:
#0 [internal function]: Symfony\Flex\Flex->truncatePackages(Object(Composer\Plugin\PrePoolCreateEvent))
#1 phar:///usr/local/bin/composer2/src/Composer/EventDispatcher/EventDispatcher.php(170): call_user_func(Array, Object(Composer\Plugin\PrePoolCreateEvent))
#2 phar:///usr/local/bin/composer2/src/Composer/EventDispatcher/EventDispatcher.php(91): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Plugin\PrePoolCreateEvent))
#3 phar:///usr/local/bin/composer2/src/Composer/DependencyResolver/PoolBuilder.php(236): Composer\EventDispatcher\EventDispatcher->dispatch('pre-pool-create', Object(Composer\Plugin\PrePoolCreateEvent))
#4 phar:///usr/local/bin/composer2/src/Composer/Repository/RepositorySet.php(233): Composer\DependencyResolver\PoolBuilder->buildPool(Array, Object(Composer\DependencyResolver\Reques in /Code/foo/vendor/symfony/flex/src/Flex.php on line 885
```

Thanks

**Comment by bendavies** [comment]
Closing.

Saw from the stack trace that somehow some old `composer2` binary was being used, rather than the `composer` on my path.

```bash
composer2 --version
Composer version 2.0.0-alpha2 2020-06-24 21:36:18
```
maybe worth looking into why something in the chain of tooling is using that old `composer2` binary and not `composer`.

Anyway, I removed this old version and we are fine.
