### ISSUE TITLE
Installing symfony flex 1.16.1 fails with composer 1.10.20 and php 7.3

### ISSUE THREAD

**Issue by oliverde8** [symfony/flex#811]
```
composer global require symfony/flex
Changed current directory to /builds/myproject/composercache
Using version ^1.16 for symfony/flex
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing symfony/flex (v1.16.1): Downloading (connecting...)Downloading (0%)           Downloading (10%)Downloading (60%)Downloading (70%)Downloading (80%)Downloading (100%)
Fatal error: Uncaught Error: Call to undefined method Symfony\Flex\ParallelDownloader::getOrigin() in /builds/myproject/composercache/vendor/symfony/flex/src/Downloader.php:316
Stack trace:
#0 /builds/myproject/composercache/vendor/symfony/flex/src/ParallelDownloader.php(278): Symfony\Flex\Downloader->Symfony\Flex\{closure}('https://flex.sy...')
#1 /builds/myproject/composercache/vendor/symfony/flex/src/ParallelDownloader.php(90): Symfony\Flex\ParallelDownloader->getNext()
#2 /builds/myproject/composercache/vendor/symfony/flex/src/Downloader.php(323): Symfony\Flex\ParallelDownloader->download(Array, Object(Closure))
#3 /builds/myproject/composercache/vendor/symfony/flex/src/Downloader.php(118): Symfony\Flex\Downloader->get(Array)
#4 /builds/myproject/composercache/vendor/symfony/flex/src/PackageResolver.php(61): Symfony\Flex\Downloader->getVersions()
#5 /builds/myproject/composercache/vendor/symfony/flex/src/PackageResolver.php(49): Symfony\Flex\PackageResolver->parseVersion('symfony/flex', '', true)
#6 /builds/myproject/ in /builds/myproject/composercache/vendor/symfony/flex/src/Downloader.php on line 316
```

https://github.com/symfony/flex/blob/main/src/Downloader.php#L316
Which wasn't present in the 1.15 version
https://github.com/symfony/flex/blob/v1.15.4/src/Downloader.php#L186

We have reverted to using the 1.15 version, and this fixed are issues until we migrate our code base. 

Regards,

**Comment by nicolas-grekas** [comment]
thanks for the report,should be fixed in v1.16.2
