### ISSUE TITLE
Call to undefined method Symfony\Flex\Recipe::getFormattedOrigin()

### ISSUE THREAD

**Issue by RikudouSage** [symfony/flex#863]
Same error as in #837 but deleting ~/.composer didn't help.

PHP: 8.0.14, 8.1.1
Composer: 2.2.5
Symfony CLI: 5.3.0
Command: `symfony new --version=lts --no-git test`

Output:

```
* Creating a new Symfony 5.4 project with Composer
  (running /usr/local/bin/composer create-project symfony/skeleton /home/username/PhpstormProjects/tests/test 5.4.* --no-interaction)

Creating a "symfony/skeleton" project at "./test"
For additional security you should declare the allow-plugins config with a list of packages names that are allowed to run code. See https://getcomposer.org/allow-plugins
You have until July 2022 to add the setting. Composer will then switch the default behavior to disallow all plugins.
Installing symfony/skeleton (v5.4.99)
  - Installing symfony/skeleton (v5.4.99): Extracting archive
Created project in /home/username/PhpstormProjects/tests/test
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking symfony/flex (v2.1.4)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing symfony/flex (v2.1.4): Extracting archive
Generating optimized autoload files
1 package you are using is looking for funding.
Use the `composer fund` command to find out more!

Symfony operations: 1 recipe (3832f17c9de8e56f3fb06a31a7473a5a)
PHP Fatal error:  Uncaught Error: Call to undefined method Symfony\Flex\Recipe::getFormattedOrigin() in phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(282) : eval()'d code:376
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(282) : eval()'d code(254): Symfony\Flex\Flex_composer_tmp0->install()
#1 [internal function]: Symfony\Flex\Flex_composer_tmp0->update()
#2 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(192): call_user_func()
#3 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(119): Composer\EventDispatcher\EventDispatcher->doDispatch()
#4 phar:///usr/local/bin/composer/src/Composer/Installer.php(372): Composer\EventDispatcher\EventDispatcher->dispatchScript()
#5 phar:///usr/local/bin/composer/src/Composer/Command/CreateProjectCommand.php(271): Composer\Installer->run()
#6 phar:///usr/local/bin/composer/src/Composer/Command/CreateProjectCommand.php(168): Composer\Command\CreateProjectCommand->installProject()
#7 phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php(245): Composer\Command\CreateProjectCommand->execute()
#8 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run()
#9 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand()
#10 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(336): Symfony\Component\Console\Application->doRun()
#11 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun()
#12 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(131): Symfony\Component\Console\Application->run()
#13 phar:///usr/local/bin/composer/bin/composer(83): Composer\Console\Application->run()
#14 /usr/local/bin/composer(29): require('...')
#15 {main}
  thrown in phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(282) : eval()'d code on line 376

Fatal error: Uncaught Error: Call to undefined method Symfony\Flex\Recipe::getFormattedOrigin() in phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(282) : eval()'d code:376
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(282) : eval()'d code(254): Symfony\Flex\Flex_composer_tmp0->install()
#1 [internal function]: Symfony\Flex\Flex_composer_tmp0->update()
#2 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(192): call_user_func()
#3 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(119): Composer\EventDispatcher\EventDispatcher->doDispatch()
#4 phar:///usr/local/bin/composer/src/Composer/Installer.php(372): Composer\EventDispatcher\EventDispatcher->dispatchScript()
#5 phar:///usr/local/bin/composer/src/Composer/Command/CreateProjectCommand.php(271): Composer\Installer->run()
#6 phar:///usr/local/bin/composer/src/Composer/Command/CreateProjectCommand.php(168): Composer\Command\CreateProjectCommand->installProject()
#7 phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php(245): Composer\Command\CreateProjectCommand->execute()
#8 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run()
#9 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand()
#10 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(336): Symfony\Component\Console\Application->doRun()
#11 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun()
#12 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(131): Symfony\Component\Console\Application->run()
#13 phar:///usr/local/bin/composer/bin/composer(83): Composer\Console\Application->run()
#14 /usr/local/bin/composer(29): require('...')
#15 {main}
  thrown in phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(282) : eval()'d code on line 376


  unable to run /usr/local/bin/composer create-project symfony/skeleton /home/username/PhpstormProjects/tests/test 5.4.
  * --no-interaction
```

**Comment by nicolas-grekas** [comment]
You should also remove your vendor/ folder I guess.

**Comment by RikudouSage** [comment]
Which vendor folder do you mean? It's a new project I'm creating, not an existing one.

**Comment by eudojosegonzalez** [comment]
Hi i have same problem

PHP Fatal error:  Uncaught Error: Call to undefined method Symfony\Flex\Recipe::getFormattedOrigin() in phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(221) : eval()'d code:476
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(221) : eval()'d code(354): Symfony\Flex\Flex_composer_tmp3->install()
#1 [internal function]: Symfony\Flex\Flex_composer_tmp3->update()
#2 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(174): call_user_func()
#3 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(102): Composer\EventDispatcher\EventDispatcher->doDispatch()
#4 phar:///usr/local/bin/composer/src/Composer/Installer.php(341): Composer\EventDispatcher\EventDispatcher->dispatchScript()
#5 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(221) : eval()'d code(947): Composer\Installer->run()
#6 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(221) : eval()'d code(387): Symfony\Flex\Flex_compo in phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(221) : eval()'d code on line 476

Fatal error: Uncaught Error: Call to undefined method Symfony\Flex\Recipe::getFormattedOrigin() in phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(221) : eval()'d code:476
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(221) : eval()'d code(354): Symfony\Flex\Flex_composer_tmp3->install()
#1 [internal function]: Symfony\Flex\Flex_composer_tmp3->update()
#2 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(174): call_user_func()
#3 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(102): Composer\EventDispatcher\EventDispatcher->doDispatch()
#4 phar:///usr/local/bin/composer/src/Composer/Installer.php(341): Composer\EventDispatcher\EventDispatcher->dispatchScript()
#5 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(221) : eval()'d code(947): Composer\Installer->run()
#6 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(221) : eval()'d code(387): Symfony\Flex\Flex_compo in phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(221) : eval()'d code on line 476

PHP 7.4.26
Composer version 2.0.11
symfony CLI version 5.3.4 
command -> symfony new project

**Comment by nicolas-grekas** [comment]
try `composer global update symfony/flex`?

**Comment by RikudouSage** [comment]
Not installed globally in my case: 

`Package "symfony/flex" listed for update is not locked.`
