### ISSUE TITLE
Problem with debug-pack

### ISSUE THREAD

**Issue by szepczynski** [symfony/flex#94]
How to reproduce:

```
$ composer create-project symfony/skeleton debug-pack-test
$ cd debug-pack-test
```

modify composer.json adding:
```
{
    ...
    "prefer-stable": true,
    "minimum-stability": "dev",
    ...
}
```

Without that I got:
```
$ composer require debug-pack
Using version ^1.0 for symfony/debug-pack
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for symfony/debug-pack ^1.0 -> satisfiable by symfony/debug-pack[v1.0.0].
    - symfony/debug-pack v1.0.0 requires easycorp/easy-log-handler dev-master -> satisfiable by easycorp/easy-log-handler[dev-master] but these conflict with your requirements or minimum-stability.
```

Next I run:

```
$ composer req orm
$ composer req migrations
$ composer req phpunit
```

And finally:
```
$ composer req debug-pack
Using version ^1.0 for symfony/debug-pack
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 12 installs, 0 updates, 0 removals
  - Installing symfony/var-dumper (v3.3.0): Loading from cache
  - Installing symfony/phpunit-bridge (v3.3.0): Loading from cache
    Detected auto-configuration settings for "symfony/phpunit-bridge"
    Setting configuration and copying files
    Adding entries to .gitignore
  - Installing twig/twig (v2.3.2): Loading from cache
  - Installing symfony/twig-bridge (v3.3.0): Loading from cache
  - Installing paragonie/random_compat (v2.0.10): Loading from cache
  - Installing symfony/polyfill-php70 (v1.3.0): Loading from cache
  - Installing symfony/web-profiler-bundle (v3.3.0): Loading from cache
    Detected auto-configuration settings for "symfony/web-profiler-bundle"
    Enabling the package as a Symfony bundle
    Setting configuration and copying files
  - Installing monolog/monolog (1.22.1): Loading from cache
  - Installing easycorp/easy-log-handler (dev-master 25d508d): Loading from cache
    Detected auto-configuration settings for "easycorp/easy-log-handler"
    Setting configuration and copying files
  - Installing symfony/monolog-bridge (v3.3.0): Loading from cache
  - Installing symfony/monolog-bundle (v3.1.0): Loading from cache
    Detected auto-configuration settings for "symfony/monolog-bundle"
    Enabling the package as a Symfony bundle
    Setting configuration and copying files
Writing lock file
Generating autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
Executing script make cache-warmup [OK]
Executing script assets:install --symlink --relative %WEB_DIR% [KO]
 [KO]
Script assets:install --symlink --relative %WEB_DIR% returned with error code 255
!!  PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The service "web_profiler.controller.profiler" has a dependency on a non-existent service "twig". in /vagrant/public/debug-pack-test/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:31
!!  Stack trace:
!!  #0 /vagrant/public/debug-pack-test/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php(57): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processValue(Object(Symfony\Component\DependencyInjection\Reference), false)
!!  #1 /vagrant/public/debug-pack-test/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(35): Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue(Array, false)
!!  #2 /vagrant/public/debug-pack-test/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php(64): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidRefer in /vagrant/public/debug-pack-test/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php on line 31
!!
!!

Installation failed, reverting ./composer.json to its original content.
```

composer.json and composer.lock are included to this issue

[composer.zip](https://github.com/symfony/flex/files/1041084/composer.zip)

**Comment by stof** [comment]
see https://github.com/symfony/debug-pack/pull/1 changing the debug-pack to allow stable versions of the dependency

**Comment by szepczynski** [comment]
@stof I'm not sure changing requirements of `easycorp/easy-log-handler` resolves this problem.

I check one more option that works:

```
$ composer create-project symfony/skeleton debug-pack-test
$ cd debug-pack-test
```

modify composer.json adding:
```
{
    ...
    "prefer-stable": true,
    "minimum-stability": "dev",
    ...
}
```

Next I run:

```
$ composer req orm
$ composer req migrations
$ composer req phpunit
```

And one more step, that i mentioned:
```
$ composer req templating
Using version ^3.3 for symfony/twig-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 3 installs, 0 updates, 0 removals
  - Installing twig/twig (v2.3.2): Loading from cache
  - Installing symfony/twig-bridge (v3.3.0): Loading from cache
  - Installing symfony/twig-bundle (v3.3.0): Loading from cache
    Detected auto-configuration settings for "symfony/twig-bundle"
    Enabling the package as a Symfony bundle
    Setting configuration and copying files
Writing lock file
Generating autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
Executing script make cache-warmup [OK]
Executing script assets:install --symlink --relative %WEB_DIR% [OK]
```

And finally:

```
$ composer req debug-pack
Using version ^1.0 for symfony/debug-pack
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 10 installs, 0 updates, 0 removals
  - Installing symfony/var-dumper (v3.3.0): Loading from cache
  - Installing symfony/phpunit-bridge (v3.3.0): Loading from cache
    Detected auto-configuration settings for "symfony/phpunit-bridge"
    Setting configuration and copying files
    Adding entries to .gitignore
  - Installing paragonie/random_compat (v2.0.10): Loading from cache
  - Installing symfony/polyfill-php70 (v1.3.0): Loading from cache
  - Installing symfony/web-profiler-bundle (v3.3.0): Loading from cache
    Detected auto-configuration settings for "symfony/web-profiler-bundle"
    Enabling the package as a Symfony bundle
    Setting configuration and copying files
  - Installing monolog/monolog (1.22.1): Loading from cache
  - Installing easycorp/easy-log-handler (dev-master 25d508d): Loading from cache
    Detected auto-configuration settings for "easycorp/easy-log-handler"
    Setting configuration and copying files
  - Installing symfony/monolog-bridge (v3.3.0): Loading from cache
  - Installing symfony/monolog-bundle (v3.1.0): Loading from cache
    Detected auto-configuration settings for "symfony/monolog-bundle"
    Enabling the package as a Symfony bundle
    Setting configuration and copying files
Writing lock file
Generating autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
Executing script make cache-warmup [OK]
Executing script assets:install --symlink --relative %WEB_DIR% [OK]
```

And voilà!

**Comment by szepczynski** [comment]
I observe that these instructions also works, because skipping `assets:install`:

```
$ composer create-project symfony/skeleton debug-pack-test
```

modify composer.json adding:
```
{
    ...
    "prefer-stable": true,
    "minimum-stability": "dev",
    ...
}
```

And:

```
$ composer req debug-pack
Using version ^1.0 for symfony/debug-pack
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 12 installs, 0 updates, 0 removals
  - Installing symfony/var-dumper (v3.3.0): Loading from cache
  - Installing symfony/phpunit-bridge (v3.3.0): Loading from cache
    Detected auto-configuration settings for "symfony/phpunit-bridge"
    Setting configuration and copying files
    Adding entries to .gitignore
  - Installing twig/twig (v2.3.2): Loading from cache
  - Installing symfony/twig-bridge (v3.3.0): Loading from cache
  - Installing paragonie/random_compat (v2.0.10): Loading from cache
  - Installing symfony/polyfill-php70 (v1.3.0): Loading from cache
  - Installing symfony/web-profiler-bundle (v3.3.0): Loading from cache
    Detected auto-configuration settings for "symfony/web-profiler-bundle"
    Enabling the package as a Symfony bundle
    Setting configuration and copying files
  - Installing monolog/monolog (1.22.1): Loading from cache
  - Installing easycorp/easy-log-handler (dev-master 25d508d): Loading from cache
    Detected auto-configuration settings for "easycorp/easy-log-handler"
    Setting configuration and copying files
  - Installing symfony/monolog-bridge (v3.3.0): Loading from cache
  - Installing symfony/monolog-bundle (v3.1.0): Loading from cache
    Detected auto-configuration settings for "symfony/monolog-bundle"
    Enabling the package as a Symfony bundle
    Setting configuration and copying files
Writing lock file
Generating autoload files
Executing script make cache-warmup [OK]
Skipping "assets:install --symlink --relative web" (needs symfony/console to run).
```

**Comment by stof** [comment]
well, the PR on the debug pack solves your first issue about resolving deps.

for the second issue, it is because the profiler needs TwigBundle too. So we would have to add 1 more dependency in the debug-pack

**Comment by stof** [comment]
The second issue you get will be solved by https://github.com/symfony/debug-pack/pull/2

**Comment by fabpot** [comment]
All fixed now
